import type { AlternativePage } from "../competitors";

// Sources for every Deep Personality fact on this page (all fetched October 8, 2026):
//   https://deeppersonality.app (homepage; canonical domain per its own <link rel="canonical">)
//   https://deeppersonality.app/pricing ("Prices last updated October 7, 2026")
//   https://deeppersonality.app/about (instrument list, 35-50 minutes, 10,000+ word report)
//   https://deeppersonality.app/sample-report (fictional "Alexa" demo: 14 AI-generated chapters)
//   https://deeppersonality.app/big-five-test (10-item IPIP teaser, IPIP-50 domain scores with percentiles)
//   https://deeppersonality.app/terms (interpretations generated by AI language models)
//   https://deeppersonality.app/privacy (Deep Personality Inc., British Columbia, Canada; adults 18+)
// deeppersonality.ai did not resolve (DNS lookup failed) on October 8, 2026.
// Deeper Signals, mentioned once for "deeper personality" searchers, is a separate company:
//   https://www.deepersignals.com/ (workplace personality assessments for organizations and coaches)
// Left out because only third-party listings say it: founder names, Product Hunt launch details,
// "top 5 fights" predictions, dating-profile writing, exported ChatGPT/Claude prompts, $19 one-time price
// (Deep Personality's own pricing page says that price is out of date).
// Other alternatives named in prose, checked on their own homepages October 8, 2026:
//   https://www.truity.com/ (free Enneagram, Big Five, DISC, and TypeFinder tests)
//   https://www.viacharacter.org/ (free survey, 24 character strengths)
//   https://www.16personalities.com/ (free test, about 10 minutes, type descriptions)

export const deepPersonalityAlternativesPage: AlternativePage = {
  slug: "deep-personality-alternatives",
  competitorName: "Deep Personality",
  title: "Deep Personality Alternatives",
  seoTitle: "Deep Personality Alternatives and How They Compare",
  description: "Deep Personality alternatives compared: what deeppersonality.app measures, how Opinion DNA's 48 dimensions and 179 questions differ, and who each test suits.",
  intro:
    "If you were looking for Deep Personality itself, its official site is [deeppersonality.app](https://deeppersonality.app). Opinion DNA is not affiliated with Deep Personality or Deep Personality Inc., and they have not reviewed or endorsed this page. We wrote it because people searching for Deep Personality sometimes end up here, and the least we can do is point them to the right place and explain how the two products differ.\n\n" +
    "Everything we say about Deep Personality below comes from its own public pages (homepage, pricing, about, sample report, terms, and privacy policy), read in October 2026. Where its site is silent on something, so are we.\n\n" +
    "The short version: Deep Personality is built around the Big Five, attachment style, and a battery of wellbeing and neurodiversity screeners, read together into a long AI-written profile, with an optional partner comparison. Opinion DNA is built around personality, values, and thinking style: 48 dimensions from 179 questions in about 10 to 15 minutes, with an AI-written report on top. They overlap in places, and they answer different questions about you. The rest of this page covers what each one measures, where they differ, who each suits, and a few other tests worth knowing about.",
  whySwitch: [
    "You want a shorter sitting: Deep Personality's site puts its full assessment at 35 to 50 minutes, and some alternatives take 10 to 15 minutes.",
    "You prefer a single one-time payment to a monthly plan (as of October 2026, Deep Personality's paid plans start at $9.99 per month, with a $149 lifetime option).",
    "You care more about values, moral reasoning, and thinking style than about wellbeing or neurodiversity screening.",
    "You only want a free, standalone Big Five score and do not need a written report.",
  ],
  alternatives: [
    // Deep Personality itself is described in "What Deep Personality offers"
    // below, not listed here as an alternative to itself.
    "opinion-dna",
    "big-five",
    "truity",
    "via",
    "16personalities",
  ],
  sections: [
    {
      heading: "What Deep Personality offers",
      content:
        "Deep Personality is a web-based assessment run by Deep Personality Inc., which its privacy policy says is based in British Columbia, Canada. The product is for adults. Here is how its own site describes it as of October 2026.\n\n" +
        "### Format\n\n" +
        "You can start without an account or a credit card. The free entry point is a short quiz of ten items from the public-domain IPIP pool, two per Big Five trait. The site calls this a teaser: it gives a first read and an archetype, and it does not score attachment. The full assessment scores the IPIP-50 (ten items per trait, reported as five domain scores with percentiles) and then measures attachment style. The homepage and about page describe the complete battery as 28 research-backed instruments taking 35 to 50 minutes.\n\n" +
        "### What it measures\n\n" +
        "Instruments named on its homepage and about page include:\n\n" +
        "- Big Five personality (IPIP-50)\n" +
        "- Attachment (ECR-R)\n" +
        "- Anxiety (GAD-7) and mood (PHQ-9)\n" +
        "- Stress response (PCL-5) and perceived stress (PSS-10)\n" +
        "- Compulsive patterns (OCI-R)\n" +
        "- ADHD (ASRS) and autism (AQ-10) screeners\n" +
        "- Life satisfaction (SWLS) and career fit (RIASEC)\n" +
        "- Self-esteem, coping, grit, mindfulness, optimism, need for cognition, empathy, emotional intelligence, locus of control, distress tolerance, perfectionism, and cognitive reflection\n\n" +
        "The site is direct that the clinical-style measures are screening tools that do not diagnose anything, and that the product as a whole is for personal self-reflection.\n\n" +
        "### How results are delivered\n\n" +
        "The paid report is a written profile that the site describes as 10,000 words or more. Its public sample report, built on a fictional demo profile, shows 14 AI-generated chapters, including identity, personality, values and motivation, strengths and blind spots, working life, romantic compatibility, friendship, relationship patterns, and wellbeing. Its terms state that the interpretations are generated by AI language models. If two people both finish the full assessment, a partner comparison puts the two profiles side by side, and the about page says it highlights trait gaps and likely friction points.\n\n" +
        "### Pricing\n\n" +
        "Its [pricing page](https://deeppersonality.app/pricing), last updated October 7, 2026, lists a free teaser, an Individual plan at $9.99 per month, a Comparison plan at $14.99 per month, one-year gifts at $29 (Individual) or $49 (Comparison), and lifetime access at $149 once. The same page notes that older third-party listings quoting a $19 or $29 one-time price are out of date.",
    },
    {
      heading: "What Opinion DNA measures",
      content:
        "Opinion DNA starts from a different question: why you think what you think. The assessment is 179 statements answered on an agree-disagree scale, which takes about 10 to 15 minutes. Your answers are scored into 48 continuous dimensions, each on a 0 to 100 scale and shown next to the population average, in three layers:\n\n" +
        "- Personality (12): the Big Five, the Dark Triad (Machiavellianism, narcissism, psychopathy) measured as everyday trait continua, two emotion-regulation styles, mortality concern, and life satisfaction\n" +
        "- Values (24): five moral foundations, seven cooperative virtues, ten personal values from Schwartz's model, plus social dominance and authoritarianism\n" +
        "- Meta-Thinking (12): thinking-style measures such as dogmatism, need for cognition, intellectual humility, and intolerance for uncertainty, plus primal world beliefs about whether the world is safe, good, alive, and enticing\n\n" +
        "A few examples of how these read in practice. Your score on [care](/dimensions/care) next to your score on [fairness](/dimensions/fairness) says a lot about which moral arguments land with you and which leave you cold. [Intellectual humility](/dimensions/intellectual-humility) describes how readily you revise a view when the evidence turns. [Self-direction](/dimensions/self-direction) shows how much you need to set your own course, and it reads differently depending on where you sit on [conformity](/dimensions/conformity).\n\n" +
        "Once your scores are calculated, AI reads your specific combination and writes a personal report covering personality, values, meta-thinking, career, and relationships. The scores come from your answers; the AI's job is interpretation. Opinion DNA is a $47 one-time purchase with lifetime access and a 30-day money-back guarantee. It was built over three years with more than 60 experts from Oxford, Cambridge, NYU, Royal Holloway, and UPenn, using peer-reviewed psychometric scales. Our [48-dimension personality test](/tests/48-dimension-personality-test) page walks through every dimension, and the [methodology](/methodology) page explains how the scoring works.",
    },
    {
      heading: "How Deep Personality and Opinion DNA differ",
      content:
        "### Where they overlap\n\n" +
        "Both score the Big Five on continuous scales instead of assigning a type. Both touch on life satisfaction, need for cognition, and personal values in some form. Both turn the scores into a long AI-written interpretation, and both offer a way to compare two people. If the Big Five is all you care about, either one will give you a usable read.\n\n" +
        "### Where they differ\n\n" +
        "- Clinical-style screening: Deep Personality runs screeners for anxiety, mood, stress response, compulsive patterns, ADHD, and autism, and reads them against your personality. Opinion DNA has no screeners, and its methodology page is explicit that it is not a clinical or diagnostic tool.\n" +
        "- Attachment: attachment style is a core part of Deep Personality's full assessment. Opinion DNA does not measure attachment.\n" +
        "- Values and moral reasoning: Opinion DNA gives values 24 of its 48 dimensions, including moral foundations such as [loyalty](/dimensions/loyalty) and [authority](/dimensions/authority), cooperative virtues, and social orientation. Those three families are not among the instruments Deep Personality lists.\n" +
        "- Thinking style and worldview: Opinion DNA's Meta-Thinking layer covers dogmatism, intolerance for uncertainty, and primal world beliefs such as whether you see the world as [safe](/dimensions/safe-world-belief) or dangerous. Deep Personality's list includes need for cognition and cognitive reflection; worldview beliefs do not appear on it.\n" +
        "- Time and payment: Deep Personality's full assessment runs 35 to 50 minutes and is sold monthly or as a $149 lifetime plan. Opinion DNA takes 10 to 15 minutes and costs $47 once.\n\n" +
        "Neither product hands you a four-letter type, and neither claims to diagnose anything. The difference is mostly about which parts of you each one points its questions at.",
      table: {
        columns: ["", "Deep Personality", "Opinion DNA"],
        rows: [
          ["Core focus", "Big Five, attachment, wellbeing and neurodiversity screeners", "Personality, values, and thinking style"],
          ["What gets scored", "28 instruments, including IPIP-50 Big Five domains with percentiles", "48 continuous dimensions, 0 to 100, next to population averages"],
          ["Length", "35 to 50 minutes for the full assessment", "179 questions, about 10 to 15 minutes"],
          ["Clinical-style screeners", "Yes (for example GAD-7, PHQ-9, ASRS, AQ-10), which its site labels as screening tools", "None; not a clinical or diagnostic tool"],
          ["Attachment style", "Yes (ECR-R)", "Not measured"],
          ["Moral foundations and cooperative virtues", "Not among its listed instruments", "Yes, 12 dimensions"],
          ["Report", "10,000+ word profile (per its site) in AI-generated chapters", "AI-written report on personality, values, meta-thinking, career, and relationships"],
          ["Comparison", "Partner comparison once two people finish", "Separate comparison reports for couples, friends, co-founders, and teams"],
          ["Price (October 2026)", "Free teaser; $9.99/month, $14.99/month with comparison, or $149 lifetime", "$47 one-time, lifetime access, 30-day money-back guarantee"],
        ],
        highlightColumn: 2,
        note: "Deep Personality details come from its homepage, about, pricing, and sample report pages at deeppersonality.app, checked October 8, 2026. Prices change, so check its site before buying.",
      },
    },
    {
      heading: "Other Deep Personality alternatives worth knowing",
      content:
        "Depending on what drew you to Deep Personality in the first place, one of these may fit better than either product above.\n\n" +
        "### A free Big Five test\n\n" +
        "Deep Personality's Big Five scores come from the IPIP-50, a public-domain inventory, and free IPIP-based Big Five tests are widely available. If five trait scores are all you want, start there. Our [Big Five alternatives](/alternatives/big-five-alternatives) page covers what a Big Five profile leaves out, such as values and thinking style.\n\n" +
        "### Truity\n\n" +
        "Truity offers several separate free tests, including the Big Five, the Enneagram, DISC, and its type-based TypeFinder. It suits people who want to choose a framework rather than sit one long combined battery. The [Opinion DNA vs Truity](/vs/opinion-dna-vs-truity) comparison goes into more detail.\n\n" +
        "### VIA Character Strengths\n\n" +
        "The VIA survey is free and produces a profile of 24 character strengths. Its focus is on what you do well, which makes it a gentle companion to anything that includes screeners. See [Opinion DNA vs VIA](/vs/opinion-dna-vs-via-character-strengths).\n\n" +
        "### 16Personalities\n\n" +
        "16Personalities is a free test of about 10 minutes built around personality types, with long free type descriptions. It sits at the other end from Deep Personality: quick, type-based, and easy to share. Our [16Personalities comparison](/vs/opinion-dna-vs-16personalities) explains the trade-offs of types against continuous scores.\n\n" +
        "### If you searched for \"deeper personality\"\n\n" +
        "You may have meant Deeper Signals (deepersignals.com), a separate company that sells personality, values, and cognitive assessments to organizations and coaches for hiring and development. It is unrelated to both Deep Personality and Opinion DNA.",
    },
    {
      heading: "Which one suits you",
      content:
        "### Deep Personality is probably the better fit if\n\n" +
        "- you want attachment style measured alongside your personality\n" +
        "- you are trying to tell whether a pattern looks more like anxiety, ADHD, or plain temperament, and you want validated screeners you can take to a professional\n" +
        "- you want a long narrative report and a partner comparison, and 35 to 50 minutes is fine\n" +
        "- a monthly plan or the lifetime option suits how you buy things\n\n" +
        "### Opinion DNA is probably the better fit if\n\n" +
        "- you want your values and moral reasoning measured alongside your temperament\n" +
        "- you are curious about how you think: how certain you tend to be, how you handle ambiguity, and what you assume about the world\n" +
        "- you would rather spend 10 to 15 minutes and pay once\n" +
        "- you want to compare yourself with a [partner](/couples), [friends](/friends), a [co-founder](/co-founders), or a [team](/teams)\n\n" +
        "Some people will want both. They cover different ground, and the overlap (mainly the Big Five) is small enough that taking one does not make the other redundant. Neither is a diagnosis, and both companies say the same thing about that: if something in your results worries you, talk to a qualified professional.\n\n" +
        "If the values and thinking-style side of the picture is what you are after, [the full assessment](/personal-assessment) takes about 10 to 15 minutes and comes with a 30-day money-back guarantee.",
    },
  ],
  faq: [
    {
      question: "Is Opinion DNA the same as Deep Personality?",
      answer:
        "No. They are separate products from separate companies with no affiliation. Deep Personality is made by Deep Personality Inc. and lives at deeppersonality.app. Opinion DNA was founded by Turi Munthe and J. Paul Neeley and lives at opiniondna.com. You may also come across [our deep personality analysis page](/tests/deep-personality-analysis); it uses \"deep personality\" as a plain description of how much ground a test covers and has no connection to the Deep Personality product.",
    },
    {
      question: "What is the official Deep Personality website?",
      answer:
        "Deep Personality's own pages use deeppersonality.app as their address. Its privacy policy names the company as Deep Personality Inc., based in British Columbia, Canada. When we checked in October 2026, deeppersonality.ai did not resolve to a website, so if you see that address mentioned elsewhere, deeppersonality.app is the one to use.",
    },
    {
      question: "How much does Deep Personality cost?",
      answer:
        "According to its pricing page as of October 2026, Deep Personality is free to start with a ten-item teaser quiz. The full report is on the Individual plan at $9.99 per month, partner comparison is on the Comparison plan at $14.99 per month, a one-year gift costs $29 (Individual) or $49 (Comparison), and lifetime access is $149 once. Its pricing page says older third-party listings quoting $19 one-time are out of date. For reference, Opinion DNA is $47 once with lifetime access and a 30-day money-back guarantee.",
    },
    {
      question: "Does Opinion DNA screen for ADHD, anxiety, or depression?",
      answer:
        "No. Opinion DNA measures trait continua in the general population and is not a clinical or diagnostic tool. A high score on [neuroticism](/dimensions/neuroticism), for example, tells you where you sit relative to other people and is not a diagnosis of anything. Deep Personality does include screeners such as the ASRS (ADHD), GAD-7 (anxiety), and PHQ-9 (mood), and its own site describes them as screening tools that flag patterns worth taking to a professional. If you have concerns about your mental health, a qualified professional is the right next step either way.",
    },
    {
      question: "Do both tests measure the Big Five?",
      answer:
        "Yes. Deep Personality's full assessment uses the IPIP-50, a public-domain inventory with ten items per trait, reported as five domain scores with percentiles. Opinion DNA includes the Big Five among its 12 personality dimensions, from [openness](/dimensions/openness) to neuroticism, each scored 0 to 100 next to the population average. The difference is in what surrounds the Big Five: attachment and screeners in Deep Personality, values and thinking style in Opinion DNA.",
    },
    {
      question: "Can I compare my results with a partner?",
      answer:
        "With both. Deep Personality offers a partner comparison on its Comparison and Lifetime plans once two people finish the full assessment. Opinion DNA has a [couples comparison](/couples) after both partners complete the assessment, plus comparison reports for [friends](/friends), [co-founders](/co-founders), and [teams](/teams).",
    },
  ],
  relatedDimensions: ["care", "fairness", "self-direction", "intellectual-humility", "need-for-cognition", "safe-world-belief"],
  ctaHref: "/personal-assessment",
};
