import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const SITE_URL = "https://opiniondna.com";
const TITLE = "Opinion DNA® — The most complete map of your mind";
const DESCRIPTION =
  "Opinion DNA maps your personality, values, and meta-thinking across 48 dimensions to reveal why you believe what you believe, and what to do about it.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s | Opinion DNA®",
  },
  description: DESCRIPTION,
  keywords: [
    "personality test",
    "psychographic assessment",
    "opinion DNA",
    "values assessment",
    "meta-thinking",
    "self-discovery",
    "personality quiz",
    "48 dimensions",
    "Big Five personality",
    "moral foundations",
  ],
  authors: [{ name: "Opinion DNA" }],
  creator: "Opinion DNA",
  publisher: "Opinion DNA",
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    title: TITLE,
    description:
      "48 dimensions of personality, values, and meta-thinking. Built with 60+ world experts.",
    url: SITE_URL,
    siteName: "Opinion DNA",
    type: "website",
    locale: "en_US",
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description:
      "48 dimensions of personality, values, and meta-thinking. Built with 60+ world experts.",
    // Twitter image auto-generated by src/app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#F5F0E8" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
